
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class FileSet
{

    public long ID { get; set; }

    public long FGID { get; set; }

    public string FileKey { get; set; }

    public string FType { get; set; }

    public string FileName { get; set; }

    public string FileEName { get; set; }

    public string FileState { get; set; }

}

}
