
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Functions
{

    public string SysCode { get; set; }

    public string GroupCode { get; set; }

    public string FuncCode { get; set; }

    public string FuncName { get; set; }

    public string FuncPath { get; set; }

    public string FuncStatus { get; set; }

    public string AuthFlag1 { get; set; }

    public string AuthName1 { get; set; }

    public string AuthFlag2 { get; set; }

    public string AuthName2 { get; set; }

    public string AuthFlag3 { get; set; }

    public string AuthName3 { get; set; }

    public string AuthFlag4 { get; set; }

    public string AuthName4 { get; set; }

    public string AuthFlag5 { get; set; }

    public string AuthName5 { get; set; }

    public int CreateMan { get; set; }

    public System.DateTime CreateDate { get; set; }

}

}
