
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class OTPToken
{

    public int ID { get; set; }

    public int UserID { get; set; }

    public string ReqSysCode { get; set; }

    public string RspSysCode { get; set; }

    public string OTPTokenKey { get; set; }

    public string OTPStatus { get; set; }

    public System.DateTime RegTime { get; set; }

}

}
