
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Pinned_Question
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pinned_Question()
    {

        this.Personal_Pinned_Question = new HashSet<Personal_Pinned_Question>();

        this.X1_Report_Question = new HashSet<X1_Report_Question>();

    }


    public int PinnedID { get; set; }

    public string PinnedName { get; set; }

    public bool Visible { get; set; }

    public int Index { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Personal_Pinned_Question> Personal_Pinned_Question { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<X1_Report_Question> X1_Report_Question { get; set; }

}

}
