
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class QuestionValidation
{

    public int ID { get; set; }

    public int QuestionID { get; set; }

    public string Operator { get; set; }

    public string Value { get; set; }

    public string Color { get; set; }

    public bool Normal { get; set; }

    public Nullable<int> GroupNum { get; set; }



    public virtual X1_Report_Question X1_Report_Question { get; set; }

}

}
