
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public int ID { get; set; }

    public string AccID { get; set; }

    public string UserGUID { get; set; }

    public string UseState { get; set; }

    public System.DateTime StateUDate { get; set; }

    public int StateUMan { get; set; }

    public string UserStatus { get; set; }

    public System.DateTime StatusUDate { get; set; }

    public int StatusUMan { get; set; }

    public string IsAdmin { get; set; }

    public int CreateMan { get; set; }

    public int UpdateMan { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime ModifyDate { get; set; }

    public bool Hidden { get; set; }

    public bool Valid { get; set; }

    public string AccName { get; set; }

    public string DoctorNo { get; set; }

    public int Senior { get; set; }

}

}
