
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class X1_PatientInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public X1_PatientInfo()
    {

        this.Personal_Pinned_Question = new HashSet<Personal_Pinned_Question>();

        this.Schedule = new HashSet<Schedule>();

        this.X1_PatientGroupMap = new HashSet<X1_PatientGroupMap>();

        this.X1_Report_Answer_Main = new HashSet<X1_Report_Answer_Main>();

    }


    public int ID { get; set; }

    public int PUCountry { get; set; }

    public string PUName { get; set; }

    public string IDNo { get; set; }

    public Nullable<System.DateTime> PUDOB { get; set; }

    public string Gender { get; set; }

    public System.DateTime CreateDate { get; set; }

    public string CreateMan { get; set; }

    public System.DateTime ModifyDate { get; set; }

    public string ModifyMan { get; set; }

    public Nullable<decimal> Height { get; set; }

    public Nullable<decimal> Weight { get; set; }

    public string Phone { get; set; }

    public string Cellphone { get; set; }

    public string ContactPhone { get; set; }

    public string ContactRelation { get; set; }

    public Nullable<int> Education { get; set; }

    public string AddrCode { get; set; }

    public string HCCode { get; set; }

    public string Addr { get; set; }

    public string Domicile { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Personal_Pinned_Question> Personal_Pinned_Question { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Schedule> Schedule { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<X1_PatientGroupMap> X1_PatientGroupMap { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<X1_Report_Answer_Main> X1_Report_Answer_Main { get; set; }

}

}
