
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class X1_Report_Question
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public X1_Report_Question()
    {

        this.QuestionValidation = new HashSet<QuestionValidation>();

        this.ValidationCondition = new HashSet<ValidationCondition>();

        this.X1_Report_Answer_Detail = new HashSet<X1_Report_Answer_Detail>();

        this.X1_Report_Answer_File = new HashSet<X1_Report_Answer_File>();

        this.X1_Report_Question_File = new HashSet<X1_Report_Question_File>();

        this.Pinned_Question = new HashSet<Pinned_Question>();

    }


    public int ID { get; set; }

    public string QuestionNo { get; set; }

    public int QuestionType { get; set; }

    public int ReportID { get; set; }

    public string QuestionText { get; set; }

    public string Description { get; set; }

    public bool Required { get; set; }

    public string CodingBookTitle { get; set; }

    public int CodingBookIndex { get; set; }

    public string AnswerOption { get; set; }

    public Nullable<int> OtherAnsID { get; set; }

    public bool Pin { get; set; }

    public Nullable<int> ParentQuestID { get; set; }

    public System.Guid Guid { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuestionValidation> QuestionValidation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ValidationCondition> ValidationCondition { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<X1_Report_Answer_Detail> X1_Report_Answer_Detail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<X1_Report_Answer_File> X1_Report_Answer_File { get; set; }

    public virtual X1_Report_Main X1_Report_Main { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<X1_Report_Question_File> X1_Report_Question_File { get; set; }

    public virtual X1_Report_Question_Type X1_Report_Question_Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pinned_Question> Pinned_Question { get; set; }

}

}
