
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class X1_Report_Export_Template
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public X1_Report_Export_Template()
    {

        this.ExportTemplateExtraQuest = new HashSet<ExportTemplateExtraQuest>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public System.Guid SystemFileID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public string CreateMan { get; set; }

    public System.DateTime ModifyDate { get; set; }

    public string ModifyMan { get; set; }

    public Nullable<System.DateTime> DeleteDate { get; set; }

    public string DeleteMan { get; set; }

    public bool IsDelete { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExportTemplateExtraQuest> ExportTemplateExtraQuest { get; set; }

    public virtual SystemFile SystemFile { get; set; }

}

}
