

//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace X1APServer.Repository
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class X1APEntities : DbContext
{
    public X1APEntities()
        : base("name=X1APEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }

    public virtual DbSet<ExportTemplateExtraQuest> ExportTemplateExtraQuest { get; set; }

    public virtual DbSet<FileGroup> FileGroup { get; set; }

    public virtual DbSet<FileSet> FileSet { get; set; }

    public virtual DbSet<FuncGroup> FuncGroup { get; set; }

    public virtual DbSet<FunctionReportMap> FunctionReportMap { get; set; }

    public virtual DbSet<Functions> Functions { get; set; }

    public virtual DbSet<OTPToken> OTPToken { get; set; }

    public virtual DbSet<OTPTSysMap> OTPTSysMap { get; set; }

    public virtual DbSet<Personal_Pinned_Question> Personal_Pinned_Question { get; set; }

    public virtual DbSet<Pinned_Question> Pinned_Question { get; set; }

    public virtual DbSet<QuestionValidation> QuestionValidation { get; set; }

    public virtual DbSet<RoleAuthMap> RoleAuthMap { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Schedule> Schedule { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<SysInfo> SysInfo { get; set; }

    public virtual DbSet<SystemFile> SystemFile { get; set; }

    public virtual DbSet<TLogData> TLogData { get; set; }

    public virtual DbSet<TLogList> TLogList { get; set; }

    public virtual DbSet<TLogMain> TLogMain { get; set; }

    public virtual DbSet<UserGroup> UserGroup { get; set; }

    public virtual DbSet<UserRoleMap> UserRoleMap { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<UserToken> UserToken { get; set; }

    public virtual DbSet<ValidationCondition> ValidationCondition { get; set; }

    public virtual DbSet<X1_PatientGroup> X1_PatientGroup { get; set; }

    public virtual DbSet<X1_PatientGroupMap> X1_PatientGroupMap { get; set; }

    public virtual DbSet<X1_PatientInfo> X1_PatientInfo { get; set; }

    public virtual DbSet<X1_Report_Answer_Detail> X1_Report_Answer_Detail { get; set; }

    public virtual DbSet<X1_Report_Answer_Extra> X1_Report_Answer_Extra { get; set; }

    public virtual DbSet<X1_Report_Answer_File> X1_Report_Answer_File { get; set; }

    public virtual DbSet<X1_Report_Answer_Main> X1_Report_Answer_Main { get; set; }

    public virtual DbSet<X1_Report_Authorization> X1_Report_Authorization { get; set; }

    public virtual DbSet<X1_Report_Export_File> X1_Report_Export_File { get; set; }

    public virtual DbSet<X1_Report_Export_Template> X1_Report_Export_Template { get; set; }

    public virtual DbSet<X1_Report_Main> X1_Report_Main { get; set; }

    public virtual DbSet<X1_Report_Question> X1_Report_Question { get; set; }

    public virtual DbSet<X1_Report_Question_File> X1_Report_Question_File { get; set; }

    public virtual DbSet<X1_Report_Question_Group> X1_Report_Question_Group { get; set; }

    public virtual DbSet<X1_Report_Question_Type> X1_Report_Question_Type { get; set; }

}

}

